### ISSUE TITLE
Review Microtasks

### ISSUE THREAD

**Issue by vchrombie** [VSevagen/chaoss-microtasks#1]
Hi @VSevagen, thanks for showing interest in applying for the GrimoireLab idea and working on the microtasks as a part of the GSoC program.

You can open an issue per microtask with the title `Review Microtask <num>` in this repository. The body could be empty or contain anything you want to share (pointers to code or documentation, comments, difficulties found) about the microtask. I can help with reviewing the microtasks and suggest some improvements.

Thanks!

**Comment by VSevagen** [comment]
Sure. I'll be opening them in a while. I'm nearly about to complete the remaining task I was left with ( task-7 ). Once I push the changes, I will be opening the issues. 
Thank you for taking the time to review my work :smile:

**Comment by vchrombie** [comment]
Thanks for working on the microtasks, please make sure you submit the proposal on the GSoC website as well as add your entry in the governance repository before the deadline.
